##Steps
Importing data
Checking and removing null values
Identifying Independent features:X
Dependent feature: y which is 'Label'
Checking dataset is balanced or not 
Importing tensorflow and its libraries
Vocabulary size and copy of X
Importing nltk, re and remove special characters, do stopwords and stemming
Append all in corpus
One hot representation
Embedding representation-sentence length, padding
Create model
convert all in array to do train test 
Train Test Split
model fitting
Predictions, confusion matrix, accuracy


In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('train_fakenews.csv')

In [4]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [5]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [6]:
df.shape

(20800, 5)

In [7]:
df= df.dropna()

In [8]:
df.head()    

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [9]:
## get the independent feature
X = df.drop('label',axis=1)
y = df['label']

In [10]:
## Checking whether dataset is balanced or not between '0' & '1'
y.value_counts()

0    10361
1     7924
Name: label, dtype: int64

In [11]:
import tensorflow as tf

In [12]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Bidirectional, LSTM
from tensorflow.keras.layers import Dense 
from tensorflow.keras.layers import Bidirectional

In [13]:
##vocabulary size
voc_size=5000


In [14]:
#makeing a copy of X, to stay original as it is
messages= X.copy()

In [15]:
messages

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [16]:
import nltk
import re
from nltk.corpus import stopwords


In [17]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [18]:
#as we remove null values
messages.reset_index(inplace=True)

In [19]:
#data preprocessing 
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]',' ', messages['title'][i])
    review= review.lower()
    review= review.split()
    review= [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [20]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [21]:
onehot_repr=[one_hot(words,voc_size) for words in corpus]
print(onehot_repr)

[[1379, 1201, 1623, 17, 4396, 1477, 2904, 802, 2129, 4534], [2981, 4512, 2594, 610, 3836, 2791, 4051], [3781, 144, 3149, 3077], [44, 1221, 2035, 4225, 2138, 95], [744, 3836, 4198, 1649, 3917, 1887, 3836, 2116, 2581, 3269], [3734, 455, 2392, 3907, 3258, 2733, 1292, 4829, 4609, 1008, 725, 4493, 4975, 842, 4051], [3000, 410, 4657, 4020, 1164, 618, 4700, 2124, 3653, 1827, 1779], [4878, 3219, 1136, 3488, 526, 1743, 2733, 4613, 3653, 1827, 1779], [4854, 210, 3814, 4372, 3235, 3336, 4997, 1934, 2733, 1647], [2078, 3368, 293, 1036, 3788, 2928, 327, 1726], [348, 69, 1882, 4198, 3030, 229, 1283, 2521, 1050, 3473, 4607], [4225, 4066, 4396, 3336, 2733, 526], [552, 898, 682, 3654, 4632, 3946, 2147, 1237, 768], [4016, 4641, 1630, 3416, 2576, 729, 3757, 3653, 1827, 1779], [3260, 4475, 872, 4082, 4773, 3653, 1827, 1779], [2122, 4592, 3765, 456, 3697, 3027, 4047, 1910, 2131, 4955], [3194, 664, 4512], [4809, 1218, 2836, 4385, 2733, 2890, 3469, 4051], [578, 1447, 2594, 3572, 1937, 221, 435, 1113, 1887], 

## Embedding Representation

In [22]:
sent_length = 20
embedded_docs= pad_sequences(onehot_repr, padding= 'pre',maxlen= sent_length )
embedded_docs

array([[   0,    0,    0, ...,  802, 2129, 4534],
       [   0,    0,    0, ..., 3836, 2791, 4051],
       [   0,    0,    0, ...,  144, 3149, 3077],
       ...,
       [   0,    0,    0, ..., 3653, 1827, 1779],
       [   0,    0,    0, ...,  803, 2617,  220],
       [   0,    0,    0, ..., 3412, 4083, 1354]])

In [23]:
#Creating model 
embedding_vector_feature = 40
model= Sequential()
model.add(Embedding(voc_size, embedding_vector_feature, input_length= sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1, activation= 'sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())

C:\Users\Admin\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [24]:
import numpy as np
X_final= np.array(embedded_docs)
y_final= np.array(y)

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size= 0.33, random_state= 42)

In [26]:
#Model training 
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs= 10, batch_size=32)

Epoch 1/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 8s 12ms/step - accuracy: 0.8170 - loss: 0.3666 - val_accuracy: 0.9127 - val_loss: 0.1968
Epoch 2/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9483 - loss: 0.1294 - val_accuracy: 0.9220 - val_loss: 0.1888
Epoch 3/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9715 - loss: 0.0805 - val_accuracy: 0.9188 - val_loss: 0.2159
Epoch 4/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.9874 - loss: 0.0454 - val_accuracy: 0.9198 - val_loss: 0.2765
Epoch 5/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9937 - loss: 0.0220 - val_accuracy: 0.9160 - val_loss: 0.3756
Epoch 6/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9963 - loss: 0.0154 - val_accuracy: 0.9127 - val_loss: 0.4264
Epoch 7/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9976 - loss: 0.0111 - val_accuracy: 0.9142 - val_loss: 0.4594
Epoch 8/10
383/383 ━━━━━━━━━━━━━━━━━━━━ 4s 11ms/step - accuracy: 0.9993 - loss: 0.0038 - val_accu

In [27]:
y_pred= model.predict(X_test)

189/189 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step


In [28]:
y_pred= np.where(y_pred>=0.5,1,0)

In [29]:
y_test

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [30]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred)

array([[3155,  264],
       [ 289, 2327]], dtype=int64)

In [31]:
print(accuracy_score(y_test, y_pred))

0.9083678541839271
